server: 
  port: ${service_port:8082}


spring:
  application:
    name: scg
  config:
     # config server를 지정하지 않으면 default localhost:8888, 아래 sping.cloud.uri 보다 우선시 한다.
     #import: "optional:configserver:http://localhost:9001"
     import: "optional:configserver:${config_servers:http://localhost:9001}" 
     additional-location: scgw   
  profiles:
    active: ${profile:local}
    include: common
  cloud: 
    config:
      uri: ${config_servers:http://localhost:9001}
      name: scgw-lb
      label: main
      